### PR TITLE
feat: add orm and db libs, create initial patient model and controller

### LINKED ISSUE #1: [Part 1] As a project member, I want to create a domain for patients and legal guardians, so that I can't maintain all information up to date
"Registration form of institutionalized elderly and their legal guardian, ensuring security and protection of personal data sensitive"

TaskList:
- [x] [WIP]

### PR DESCRIPTION
**Pull request by fekow**
Initial CRUD implementation with local DB

### CODE REVIEW

**Review by rogerpoliver — DISMISSED** [review]
LGTM!!!

**Review by lipeeeg — APPROVED** [review]
👍

**Comment by rogerpoliver** [comment]
@fekow  @lipeeeg 

Just a few points, next time make sure you link to the source issue so we don't lose track and keep the board up to date. 
Describe what was implementation about, in this case, about patients and their legal guardians, "initial crud" means nothing.
Also don't forget to delete the branch.

**Comment by rogerpoliver** [comment]
Related to #1

**Pull request merged**
